version: '3.2'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command:
            bundle exec guard
        volumes:
            - .:/usr/src/app
